license="${mod_license}"

issueTrackerURL="https://github.com/alfiehanks/Immersive-Enchanting/issues"

[[mods]] #mandatory

modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory

logoFile="immersiveenchanting.png"

authors="${mod_authors}"
description='''${mod_description}'''
credits = '''Thanks to @carl_classic on Modrinth for the Enchanted Book sprites! https://modrinth.com/user/carl_classic

Thanks to everyone in The NeoForge Project Discord.'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="alfinolib"
    type="required"
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

